// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

@http:ServiceConfig {basePath: "/api/v1"}
type AlbumsService service object {
    *http:ServiceContract;
    resource function get albums() returns Album[];
    resource function post albums(@http:Payload Album payload) returns Album|ErrorPayloadBadRequest;
};

public type ErrorPayloadBadRequest record {|
    *http:BadRequest;
    ErrorPayload body;
|};

public type ErrorPayload record {
    string? timestamp;
    int? status;
    string? reason;
    string? message;
    string? path;
    string? method;
};

public type Album record {|
    string? title;
    string? artist;
|};
